### ISSUE TITLE
issue in range selection

### ISSUE THREAD

**Issue by AhmadSabeh** [ptrstovka/calendarview2#4] opened 2018-02-08 07:45 UTC
when using range selection , after selecting 2 dates all the other dates in the previous and next month are being highlighted , what seems to be the issue ?

**Comment by ptrstovka** [comment] 2018-02-09 17:34
Can you provide some code sample or gif/video?
I know that there is a lot of things to do in range selection to get it fully working but I never met with this problem. Can you provide some steps to reproduce? Then I can look at.

I have forked this library because of lack of custom drawings on range selections. But all I wanted was only some kind of "read only" calendar. Without any range selection by the user. So really there can be some issues, I didn't pay much attention on this. My plan is to get it fully working, but currently I don't have time and the project where I am using this component is currently paused.😠

**Comment by AhmadSabeh** [comment] 2018-03-05 13:43
Dear Mr. Peter,

I’m sorry for replying this late I did not notice your email until now .The issue I was facing is that all the other items were being highlighted when selecting a range in the calendar, fortunately I found out what was the issue and I will share with you the only modification I had to do :

• In the CalendarPagerAdapter Class

public void setDateRangeSelected(List<CalendarDay> days) {
    selectedDates.addAll(days);
    for (V currentView : currentViews) {

        //MODIFIED BY AHMAD SABEH, setting false will only add background to the range selected
        currentView.setSelectedDates(days, false);
    }
}

I would like to thank you for dedicating your time to making this library as it has helped me a lot in the development of a project I’m working on.

**Comment by petertraknen** [comment] 2018-04-16 14:53
@ptrstovka I have exactly the same problem. Could you update the project with the solution that @AhmadSabeh has proposed? Thank you very much for the project and very good work, this library is coming great. :)

**Comment by AhmadSabeh** [comment] 2018-04-16 15:02
@petertraknen there is another issue that i faced on the Samsung Note 5 where the highlighted part is seperated from the days on the first day of each week, I have worked around it by setting the first day of the week to monday on this specific os . not the best solution but if you managed to fix it do please mention me !

**Comment by ptrstovka** [comment] 2018-04-16 15:08
Hey guys!

Really sorry for ignoring this issue for a long time. My bad. 

Thank you for your interest in this library but currently I don't have free time to update this library. 
I would be really grateful if you will make a pull request to resolve those issues.

I will try to look at those issues within week or two. I will post a comment here. So I am reopening this issue.
But anyway, any kind of help will be appreciated.

**Comment by ptrstovka** [comment] 2018-06-04 16:05
resolved in 5ee4394c7cd96051af704d924b14a755a3f3ec5b

**Closed as completed by ptrstovka** 2018-06-04 16:05 UTC
